### ISSUE TITLE
2차 스토리보드 작성

### ISSUE THREAD

**Issue by maru536** [Alizzwell/this-play.js#3]
이슈 내용 : 
1. 튜토리얼 버튼
- 메인 화면에만 출력
- 튜토리얼이 필요한 창에 찾으면 보일정도로 (?)표시를 넣어서 튜토리얼 버튼 대체
1. 인풋 사이즈 제한 
2. 고급 사용자용 input parser, set Design Rule을 일반 사용자를 불편하게 하지 않도록 추가
3. 사이트의 주요 취지에 맞도록 설계
4. 알고리즘 리스트 카테고리를 설정을 하되, 보이는 방식은 왼쪽 카테고리 메뉴에서 원하는 카테고리를 
   체크박스에 체크하면 해당 카테고리만 보임

추후 발생하는 이슈는 추후에 추가

**Comment by baleian** [comment]
Issue moved to [Alizzwell/common #5](https://github.com/Alizzwell/common/issues/5) via [**ZenHub**](https://www.zenhub.com/)
